# Generated by Django 3.2.15 on 2023-04-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='place',
            index_together=set(),
        ),
    ]
