# Generated by Django 3.2.15 on 2023-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230406_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='with_an_error',
            field=models.BooleanField(default=False, verbose_name='Ошибка определения координат'),
        ),
    ]
