# Generated by Django 3.2.15 on 2023-04-02 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
