# Generated by Django 3.2.15 on 2023-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_productincart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработан'), ('PICKING', 'Сборка'), ('DELIVERING', 'Доставка'), ('CLOSED', 'Завершён'), ('CANCELED', 'Отменён')], db_index=True, default='NEW', max_length=10, verbose_name='Статус'),
        ),
    ]
