# Generated by Django 3.2.15 on 2023-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230404_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличка'), ('CASHLESS', 'Безнал')], db_index=True, default='CASH', max_length=10, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
